### ISSUE TITLE
Not an issue: kudos!

### ISSUE THREAD

**Issue by gonzus** [karlseguin/blog#10]
This is not really an issue, but I wanted to let you know (in case you don't already) that I found your guide from this post, and I so far find its quality to be outstanding! https://ziggit.dev/t/guide-for-learning-zig-in-english-and-chinese/1880

Maybe you could post yourself about the guide over there, and perhaps https://zig.news/

Cheers!

**Comment by karlseguin** [comment]
Thanks, appreciate the feedback. I deployed your suggestions :)
