### ISSUE TITLE
Suggestions for part 2

### ISSUE THREAD

**Issue by gonzus** [karlseguin/blog#12]
* first generic function we've `see` → first generic function we've `seen`
* while for is exclusive of the upper bound → while for is exclusive of the upper bound`.`
* The end of the range is `inferred by` the length of haystack →
  *  The end of the range is inferred `from` the length of haystack
  *  The end of the range is `implied` by the length of haystack
* the number of escape `sequence` in a string → the number of escape `sequences` in a string
* what else these `control flow` have to offer → what else these `control flow structures` have to offer
* can contain other `definition` → can contain other `definitions`
* based on its `comparisin` → based on its `comparison`
* when dealing with `enum's` → when dealing with `enums`
* an integer, `an float` or a nan → an integer, `a float` or a nan
* to leave them `unitialized` → to leave them `uninitialized`
* leaves the memory `unitialized` → leaves the memory `uninitialized`

**Comment by karlseguin** [comment]
Thanks for this, I really appreciate it. I read it over at least 10 times...but it just blurs and I just speed-read it since it's too familiar....

**Comment by zhangkaizhao** [comment]
Hi @karlseguin
I think something like [typos](https://github.com/crate-ci/typos) can be used to find and correct spelling mistakes among source code.
