### ISSUE TITLE
Suggestions for heap memory

### ISSUE THREAD

**Issue by gonzus** [karlseguin/blog#16]
* can `even be hard` to detect → can `be even harder` to detect
* I've `introduce` new syntax → I've `introduced` new syntax
* So far we've only `see` → So far we've only `seen`
* for creating `interface` → for creating `interfaces`
* There can be good `reason` → There can be good `reasons`
* is the need `for of` short-lived state → is the need `for` short-lived state

**Comment by karlseguin** [comment]
Thanks again :)
