### ISSUE TITLE
Suggestions for coding in zig

### ISSUE THREAD

**Issue by gonzus** [karlseguin/blog#18]
* type that `encapsulate` all of the memory → type that `encapsulates` all of the memory
* taken to prefixing `field` with underscore → taken to prefixing `fields` with underscore
* a function takes `an` Writer → a function takes `a` Writer
* We `previous` saw → We `previously` saw
* `to it` into a variable → `to output it` into a variable
* I wish Zig `has` interfaces → I wish Zig `had` interfaces
* the name of the type `as string` → the name of the type `as a string`
* my favorite `usage` of → my favorite `usages` of
* imagine a more complex `structures` → imagine a more complex `structure`
* two `addition` steps → two `additional` steps
* more `complicates` setups → more `complicated` setups
* adding `a our local` calc → adding `our local` calc
* can expose multiple `module` → can expose multiple `modules`
* dependencies `to on` the aggressive side → dependencies `to be on` the aggressive side

And this is code. Change
```zig
.active  = if (@hasField(T, "active")) data.name else true,
```
into
```zig
.active  = if (@hasField(T, "active")) data.active else true,
```

**Comment by karlseguin** [comment]
thanks again!
