### ISSUE TITLE
Suggestions for interfaces

### ISSUE THREAD

**Issue by gonzus** [karlseguin/blog#19]
(Only because this page was linked from the others.)
* doesn't have `an` simple mechanism → doesn't have `a` simple mechanism
* there `might` some things → there `might be` some things
* just `call` our function pointer → just `calls` our function pointer
* the implementation's `functions` is invoked → the implementation's `function` is invoked
* baked into the `union` → baked into the `union.`
* all supported caching `implementation` → all supported caching `implementations`

**Comment by karlseguin** [comment]
thanks =)
