### ISSUE TITLE
Suggestions for the array part

### ISSUE THREAD

**Issue by hshq** [karlseguin/blog#20]
> A slice's type is always derived from the underlying array. Whether b is declared const or not, the underlying array is of type [5]const i32 and so b must be of type []const i32. If we want to be able to write into b, we need to change a from a const to a var.

我刚开始学习 Zig 。
当我看到“underlying array”时，我只想到数组存储，而不是指向它的变量“a”。
如果“a”也包括在内，那么这是我理解的问题，而不是描述问题；那么这里能强调一下“a”也包括在内吗？
反之，如果不包括“a”，我认为问题在于“underlying array”的类型是“[5]i32”，而不是“[5]const i32”。
那么“[]const i32”中的“const”来自指向它的变量“a”，而不是“底层数组”。这是一个描述问题。

I just started learning Zig.
When I see "underlying array", I just think of the array storage, not the variable "a" pointing to it.
If "a" is also included, then it is a question of my understanding, not a description problem; then can you emphasize that "a" is also included?
On the contrary, if "a" is not included, I think the problem is that the type of "underlying array" is "[5]i32", not "[5]const i32".
Then the “const” in "[]const i32" comes from the variable "a" pointing to it, not "underlying array". This is a description problem.

**Comment by karlseguin** [comment]
`a` is included, but I agree it can be worded better. I changed it to:

> A slice is a length and pointer to [part of] an array. A slice's type is always derived from what it is slicing. Whether `b` is declared `const` or not, it is a slice of a `[5]const i32` and so b must be of type `[]const i32`.
