### ISSUE TITLE
learning_zig: some issues I found

### ISSUE THREAD

**Issue by perillo** [karlseguin/blog#23]
Thanks for sharing Learning Zig!

Here are some issues I found.

### comptime

When documenting how *comptime* is used when calling `std.debug.print`, you wrote that *args* is a anonymous struct literal.  This is true, but in normal case, when the field name is not specified, the struct literal is called *tuple*.

### enums

You should introduce the concept of *enum literals*, like it was done when introducing *anonymous struct literals*.

See https://ziglang.org/documentation/master/#toc-Enum-Literals

## pointers

In addition to documenting that using a *packed struct* will ensure strong guarantees about the memory layout, you should also document that an *extern struct* has in-memory layout matching the C ABI for the target.

See https://ziglang.org/documentation/master/#extern-struct

## coding_in_zig

At the end of the section there is a typo:
```txt
I'm excited by the possibility that, despite this complexity, the code mostly
made sense. It it didn't, don't give up. Pick an example and break it, add print
            ^
```

**Comment by karlseguin** [comment]
Thanks. I agree with all suggestions and have made the changes.
