### ISSUE TITLE
Zig-Interfaces: add some examples using @fieldParentPtr

### ISSUE THREAD

**Issue by perillo** [karlseguin/blog#24]
Thanks for sharing Zig-Interfaces!

In addition to a *tagged union*, simple interfaces can also be implemented using `@fieldParentPtr`.

This type of interface is used by the Zig Build System, for the build steps.

There is also a blob post with some examples: https://zig.news/david_vanderson/interfaces-in-zig-o1c/

**Comment by karlseguin** [comment]
I added a very brief mention to `@fieldParentPtr`. I think the blog post is enough without adding whole new concepts, but I agree that it's worth mentioning since, while used far less now, it still comes up.
