### ISSUE TITLE
learning zig: enum example - complete and completed

### ISSUE THREAD

**Issue by rofrol** [karlseguin/blog#41]
Why `isComplete` returns `true` if value equals `.confirmed` or `.err`, when there is already field `.completed`?

```zig
const Stage = enum {
    validate,
    awaiting_confirmation,
    confirmed,
    completed,
    err,

    fn isComplete(self: Stage) bool {
        return self == .confirmed or self == .err;
    }
};
```

**Comment by karlseguin** [comment]
I don't know. I removed the `completed` value :)

**Comment by rofrol** [comment]
Thanks. I see that I am just doing myself more work with translating ;)
