### ISSUE TITLE
Информация про создание срезов из массивов

### ISSUE THREAD

**Issue by xeonx86** [karlseguin/blog#49]
```Zig
const std = @import("std");

pub fn main() void {
    const a = [_]i32{ 1, 2, 3, 4, 5 };
    const b = a[1..4];

    std.debug.print("type of a = {any}\n", .{@TypeOf(a)});
    std.debug.print("type of b = {any}\n", .{@TypeOf(b)});
}
```

такой код выводит так как написано в книге 

```
type of a = [5]i32
type of b = *const [3]i32
```

но если использовать пример из книги 

```Zig
const a = [_]i32{1, 2, 3, 4, 5};
var end: usize = 4;
const b = a[1..end];
```

то тип ```b``` должен быть ```[]const i32```

но вот такой код 

```Zig
const std = @import("std");

pub fn main() void {
    const a = [_]i32{ 1, 2, 3, 4, 5 };
    const end: usize = 4;
    const b = a[1..end];

    std.debug.print("type of a = {any}\n", .{@TypeOf(a)});
    std.debug.print("type of b = {any}\n", .{@TypeOf(b)});
}
```
Выдает такой результат

```
type of a = [5]i32
type of b = *const [3]i32
```

Разницы нет никакой, пологаю, что компилятор научился вычеслять длинну во время компиляции даже если она находится в переменной

zig version: 0.14.0-dev.842+a655c15c4

**Comment by karlseguin** [comment]
The English version was updated to use:

```zig
const a = [_]i32{1, 2, 3, 4, 5};
var end: usize = 3;
end += 1;
const b = a[1..end];
```

It isn't pretty, but it works. 

You could open an issue in the repo of the Russian translation:
https://github.com/dee0xeed/learning-zig-rus/tree/main

When I wrote this, I wasn't thinking about translations. Unfortunately, it's very hard for the translations to track any changes that I make.
