### ISSUE TITLE
Code Snippet Error With @typeInfo(...)

### ISSUE THREAD

**Issue by caleberi** [karlseguin/blog#53]
In your previous [blog](https://www.openmymind.net/Creating-Enums-At-Comptime) , on how to create enums at comptime, there seems to be an issue with the code snippet you added in the conclusion, talking about how to extract information from `std.builtin.Type` using inline for loop as a debugging mechanism after extracting the type.

However, Zig v0.13.0 shows that using `.@"struct"` and also `.@"enum"` won't work since it has been changed to a struct or enum as shown below:

```zig
pub fn main() !void {
    const User = struct {
        id: i32,
        name: []const u8,
    };
    const info = @typeInfo(User).Struct;
    inline for (info.fields) |f| {
        std.debug.print("{any}\n", .{f});
    }
}
```

**Comment by karlseguin** [comment]
Hi, it's actually the other way around. Up until about 1 month ago, the tag names for those fields where .Struct and .Enum. 

I generally write my blog posts using master, or something close to it. It's a no-win situation, if I use a specific version (e.g. 0.13.0), then people using a more up to date version will have issues. However, by using the current master, there's a chance that the blog will remain valid for subsequent versions.

**Comment by caleberi** [comment]
Okay, I will check it out.
Thank you
