### ISSUE TITLE
Inconsistent text and code

### ISSUE THREAD

**Issue by gonzus** [karlseguin/blog#7]
In `language_overview_1` it says
```
Since our program is a single file and therefore
User is only used in the file where it's defined,
we didn't need to make it pub.
```
but the code is actually using `pub`:
```zig
pub const User = struct {
	power: u64,
	name: []const u8,
};
```

**Comment by sogaiu** [comment]
These two things:

* The code is using `pub`
* "we didn't need to make it pub"

seem consistent to me.

When I read the prose "didn't need to" in the quoted text, I hear a hint of "but we did" (^^;

**Comment by karlseguin** [comment]
Ya, this one is tough. I added "But then we wouldn't have seen how to expose a declaration to other files".
